### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/Paradox-2017#1]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by LiamNorman** [comment]
Hey I'd like to tackle this one!

**Comment by LiamNorman** [comment]
Hey @Rishabh04-02, I have updated the readme as per your samples. Let me know if you want anything changed or updated?

Thanks!
